all: jshop2

GIT_DIR=build/jshop2
GIT_URL=https://github.com/b-it-bots/jshop2.git
GIT_REVISION=83cf8893d7acd77f9ab2b2e3af4e71c4084b0c91
include $(shell rospack find mk)/git_checkout.mk

jshop2: $(GIT_DIR);
	install -dm755 "$(GIT_DIR)/bin.build"
	CLASSPATH=$(shell rospack find)/$(GIT_DIR):$(shell rospack find)/$(GIT_DIR)/antlr.jar make -C $(GIT_DIR)/

clean:
	make -C "$(GIT_DIR)/" clean

wipe: clean
	rm -rf $(GIT_DIR) build
